services:
  postgres:
    image: postgres:15

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mage"]
      interval: 10s
      timeout: 5s
      retries: 5
  mage:
    image: mageai/mageai:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
    ports:
      - "6789:6789"
    volumes:
      - mage_data:/home/src

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"

    depends_on:
      - postgres
volumes:
  postgres_data:
  mage_data: